#!/usr/bin/env python3
"""gen_ntt_kat.py - ML-KEM NTT (FIPS 203) reference + hardware KAT vectors.

Emits:
  rtl/ntt_zetas.vh   - zeta table as a Verilog localparam array
  kat/ntt_in1.txt    - input polynomial 1 (256 coeffs)
  kat/ntt_in2.txt    - input polynomial 2 (256 coeffs)
  kat/ntt_fwd1.txt   - forward NTT of poly 1
  kat/ntt_fwd2.txt   - forward NTT of poly 2
  kat/ntt_inv1.txt   - inverse NTT of fwd1 (must equal poly 1)
  kat/ntt_mul.txt    - basemul(fwd1, fwd2)  (NTT-domain product)

Coefficients are written as 3-digit lowercase hex, one per line, for
$readmemh in tb_ntt.sv.
"""

import os
import random

Q = 3329
N = 256

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def bitrev7(x):
    r = 0
    for _ in range(7):
        r = (r << 1) | (x & 1)
        x >>= 1
    return r


ZETAS = [pow(17, bitrev7(i), Q) for i in range(128)]


def ntt(f):
    f = f[:]
    k = 1
    length = 128
    while length >= 2:
        for start in range(0, N, 2 * length):
            zeta = ZETAS[k]
            k += 1
            for j in range(start, start + length):
                t = (zeta * f[j + length]) % Q
                f[j + length] = (f[j] - t) % Q
                f[j] = (f[j] + t) % Q
        length //= 2
    return f


def invntt(f):
    f = f[:]
    k = 127
    length = 2
    while length <= 128:
        for start in range(0, N, 2 * length):
            zeta = ZETAS[k]
            k -= 1
            for j in range(start, start + length):
                t = f[j]
                f[j] = (f[j] + f[j + length]) % Q
                f[j + length] = ((f[j + length] - t) * zeta) % Q
        length *= 2
    finv = pow(N // 2, Q - 2, Q)  # 128^-1 mod q
    return [(c * finv) % Q for c in f]


def basemul(a, b):
    r = [0] * N
    for p in range(128):
        zeta = ZETAS[64 + (p >> 1)]
        if p & 1:
            zeta = (Q - zeta) % Q      # odd pairs use -zetas[64+i]
        a0, a1 = a[2 * p], a[2 * p + 1]
        b0, b1 = b[2 * p], b[2 * p + 1]
        r[2 * p] = (a0 * b0 + a1 * b1 * zeta) % Q
        r[2 * p + 1] = (a0 * b1 + a1 * b0) % Q
    return r


def write_vec(path, vec):
    with open(path, "w") as f:
        for c in vec:
            f.write("%03x\n" % c)
    print("wrote %s (%d coeffs)" % (path, len(vec)))


def main():
    random.seed(20260807)
    p1 = [random.randrange(Q) for _ in range(N)]
    p2 = [random.randrange(Q) for _ in range(N)]

    f1 = ntt(p1)
    f2 = ntt(p2)
    i1 = invntt(f1)
    m = basemul(f1, f2)

    # sanity: round-trip and multiplication ring property
    assert i1 == p1, "inverse NTT round-trip failed"

    os.makedirs(os.path.join(ROOT, "kat"), exist_ok=True)

    # zeta table for the RTL (case function: Icarus lacks array parameters)
    with open(os.path.join(ROOT, "rtl", "ntt_zetas.vh"), "w") as f:
        f.write("// generated by scripts/gen_ntt_kat.py - do not edit\n")
        f.write("function [11:0] zget(input [6:0] i);\n")
        f.write("    case (i)\n")
        for i, z in enumerate(ZETAS):
            f.write("        7'd%3d: zget = 12'h%03x;\n" % (i, z))
        f.write("        default: zget = 12'h0;\n")
        f.write("    endcase\n")
        f.write("endfunction\n")
    print("wrote rtl/ntt_zetas.vh")

    write_vec(os.path.join(ROOT, "kat", "ntt_in1.txt"), p1)
    write_vec(os.path.join(ROOT, "kat", "ntt_in2.txt"), p2)
    write_vec(os.path.join(ROOT, "kat", "ntt_fwd1.txt"), f1)
    write_vec(os.path.join(ROOT, "kat", "ntt_fwd2.txt"), f2)
    write_vec(os.path.join(ROOT, "kat", "ntt_inv1.txt"), i1)
    write_vec(os.path.join(ROOT, "kat", "ntt_mul.txt"), m)


if __name__ == "__main__":
    main()
