#!/usr/bin/env python3
"""run_kat.py - NIST SHA-3 / SHAKE known-answer-test runner.

Generates a self-checking Icarus testbench from the vectors in kat/sha3/,
simulates the sha3 wrapper (rtl/sha3.v + rtl/keccak.v) and reports per-suite
PASS counts.

Usage:
    python3 scripts/run_kat.py                 # all suites
    python3 scripts/run_kat.py --suite sha3    # SHA-3 suites
    python3 scripts/run_kat.py --suite shake   # SHAKE suites
"""

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KAT_DIR = os.path.join(ROOT, "kat", "sha3")
BUILD = os.path.join(ROOT, "build", "kat")

sys.path.insert(0, os.path.join(ROOT, "scripts"))
import gen_kat as katgen  # noqa: E402


def ensure_vectors():
    """Regenerate the deterministic vectors if a fresh clone lacks them."""
    needed = [os.path.join(KAT_DIR, n) for n in SUITES]
    if any(not os.path.exists(p) for p in needed):
        katgen.main()

SUITES = {
    "sha3_256.txt": {"mode": 0, "out_len": 32},
    "sha3_512.txt": {"mode": 1, "out_len": 64},
    "shake128.txt": {"mode": 2, "out_len": 32},
    "shake256.txt": {"mode": 3, "out_len": 32},
}


def parse_vector(line):
    parts = line.split()
    n = int(parts[0], 10)
    if len(parts) == 3:
        msg = bytes.fromhex(parts[1])
        dig = bytes.fromhex(parts[2])
    else:  # empty message: "0  <digest>"
        msg = b""
        dig = bytes.fromhex(parts[1])
    assert len(msg) == n
    return msg, dig


def gen_kat(suites):
    os.makedirs(BUILD, exist_ok=True)

    msgs = []          # packed message bytes
    digs = []          # packed digest bytes
    cases = []         # (mode, len, out_len, msg_off, dig_off)

    for name, meta in suites.items():
        with open(os.path.join(KAT_DIR, name)) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                msg, dig = parse_vector(line)
                cases.append((meta["mode"], len(msg), meta["out_len"],
                              len(msgs), len(digs)))
                msgs.extend(msg)
                digs.extend(dig)

    def write_mem(path, values):
        with open(path, "w") as f:
            for v in values:
                f.write("%02x\n" % v)

    write_mem(os.path.join(BUILD, "msgs.mem"), msgs)
    write_mem(os.path.join(BUILD, "digs.mem"), digs)

    fields = {k: [] for k in ("mode", "len", "out", "moff", "doff")}
    for mode, ln, out, mo, do in cases:
        fields["mode"].append(mode)
        fields["len"].append(ln)
        fields["out"].append(out)
        fields["moff"].append(mo)
        fields["doff"].append(do)
    for k, v in fields.items():
        write_mem(os.path.join(BUILD, "cases_%s.mem" % k), v)

    return len(cases)


TB_TEMPLATE = r"""`timescale 1ns/1ps
// Auto-generated by run_kat.py - do not edit.
module tb_kat;

    reg clk = 1'b0;
    always #5 clk = ~clk;

    reg        rst_n;
    reg        bus_req;
    reg        bus_we;
    reg [7:0]  bus_addr;
    reg [31:0] bus_wdata;
    wire [31:0] bus_rdata;
    wire        bus_ack;
    wire        irq_done;

    wire        perm_req;
    wire [1599:0] perm_state_in;
    wire        perm_done;
    wire [1599:0] perm_state_out;

    sha3 dut (
        .clk(clk), .rst_n(rst_n),
        .bus_req(bus_req), .bus_we(bus_we),
        .bus_addr(bus_addr), .bus_wdata(bus_wdata),
        .bus_rdata(bus_rdata), .bus_ack(bus_ack), .irq_done(irq_done),
        .perm_req(perm_req), .perm_state_in(perm_state_in),
        .perm_done(perm_done), .perm_state_out(perm_state_out)
    );

    keccak_engine u_keccak (
        .clk(clk), .rst_n(rst_n),
        .c0_req(perm_req), .c0_state_in(perm_state_in),
        .c0_done(perm_done), .c0_state_out(perm_state_out),
        .c1_req(1'b0), .c1_state_in(1600'b0), .c1_done(), .c1_state_out(),
        .c2_req(1'b0), .c2_state_in(1600'b0), .c2_done(), .c2_state_out(),
        .c3_req(1'b0), .c3_state_in(1600'b0), .c3_done(), .c3_state_out()
    );

    localparam integer NUM_CASES = __NUM_CASES__;

    reg [7:0]  case_mode [0:NUM_CASES-1];
    reg [15:0] case_len  [0:NUM_CASES-1];
    reg [15:0] case_out  [0:NUM_CASES-1];
    reg [15:0] case_moff [0:NUM_CASES-1];
    reg [15:0] case_doff [0:NUM_CASES-1];

    reg [7:0]  msgs [0:__MSG_N__-1];
    reg [7:0]  digs [0:__DIG_N__-1];

    integer pass = 0;
    integer fail = 0;

    task bus_write;
        input [7:0]  addr;
        input [31:0] data;
        begin
            @(negedge clk);
            bus_req = 1'b1; bus_we = 1'b1;
            bus_addr = addr; bus_wdata = data;
            @(negedge clk);
            bus_req = 1'b0; bus_we = 1'b0;
        end
    endtask

    task bus_read;
        input  [7:0]  addr;
        output [31:0] val;
        begin
            @(negedge clk);
            bus_req = 1'b1; bus_we = 1'b0; bus_addr = addr;
            @(posedge clk);       // DUT latches registered reads here
            @(negedge clk);       // bus_rdata reflects the latched value
            val = bus_rdata;
            bus_req = 1'b0;
        end
    endtask

    task wait_status;
        input [1:0] bit_idx;
        input       want;
        reg [31:0] st;
        integer t;
        begin
            t = 0;
            repeat (500000) begin
                bus_read(8'h04, st);
                if (st[bit_idx] == want) return;
                t = t + 1;
            end
            $display("FAIL: timeout waiting STATUS[%0d]=%0d", bit_idx, want);
            fail = fail + 1;
        end
    endtask

    task run_case;
        input integer c;
        reg [31:0] wdata, rdata;
        integer i, len, out, nw, moff, doff, mode, mism;
        begin
            mode = case_mode[c];
            len  = case_len[c];
            out  = case_out[c];
            moff = case_moff[c];
            doff = case_doff[c];

            bus_write(8'h08, mode);                       // MODE
            bus_write(8'h14, len);                        // LEN
            nw = (len + 3) / 4;
            for (i = 0; i < nw; i = i + 1) begin
                wdata = 32'h0;
                if (i*4+0 < len) wdata[7:0]   = msgs[moff + i*4 + 0];
                if (i*4+1 < len) wdata[15:8]  = msgs[moff + i*4 + 1];
                if (i*4+2 < len) wdata[23:16] = msgs[moff + i*4 + 2];
                if (i*4+3 < len) wdata[31:24] = msgs[moff + i*4 + 3];
                bus_write(8'h0C, wdata);                  // DATA_IN
            end
            bus_write(8'h00, 32'h1);                      // absorb_start
            wait_status(1, 1'b1);
            bus_write(8'h18, out);                        // SQUEEZE_LEN
            bus_write(8'h00, 32'h2);                      // squeeze_start
            wait_status(2, 1'b1);

            mism = 0;
            nw = (out + 3) / 4;
            for (i = 0; i < nw; i = i + 1) begin
                bus_read(8'h10, rdata);
                if (i*4+0 < out && rdata[7:0]   !== digs[doff+i*4+0]) mism = mism + 1;
                if (i*4+1 < out && rdata[15:8]  !== digs[doff+i*4+1]) mism = mism + 1;
                if (i*4+2 < out && rdata[23:16] !== digs[doff+i*4+2]) mism = mism + 1;
                if (i*4+3 < out && rdata[31:24] !== digs[doff+i*4+3]) mism = mism + 1;
            end
            if (mism == 0) pass = pass + 1;
            else begin
                fail = fail + 1;
                $display("KAT FAIL case %0d (mode %0d len %0d): %0d bytes differ", c, mode, len, mism);
            end
        end
    endtask

    initial begin
        integer c;
        $readmemh("build/kat/cases_mode.mem", case_mode);
        $readmemh("build/kat/cases_len.mem", case_len);
        $readmemh("build/kat/cases_out.mem", case_out);
        $readmemh("build/kat/cases_moff.mem", case_moff);
        $readmemh("build/kat/cases_doff.mem", case_doff);
        $readmemh("build/kat/msgs.mem", msgs);
        $readmemh("build/kat/digs.mem", digs);

        rst_n = 1'b0;
        bus_req = 1'b0; bus_we = 1'b0; bus_addr = 8'h0; bus_wdata = 32'h0;
        #20 rst_n = 1'b1;
        repeat (2) @(posedge clk);

        for (c = 0; c < NUM_CASES; c = c + 1)
            run_case(c);

        $display("KAT_RESULT pass=%0d fail=%0d total=%0d", pass, fail, NUM_CASES);
        $finish;
    end
endmodule
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--suite", choices=["sha3", "shake", "all"], default="all")
    args = ap.parse_args()

    if args.suite == "sha3":
        names = ["sha3_256.txt", "sha3_512.txt"]
    elif args.suite == "shake":
        names = ["shake128.txt", "shake256.txt"]
    else:
        names = list(SUITES)

    suites = {n: SUITES[n] for n in names}
    ensure_vectors()
    ncases = gen_kat(suites)

    msgs_n = sum(1 for _ in open(os.path.join(BUILD, "msgs.mem")))
    digs_n = sum(1 for _ in open(os.path.join(BUILD, "digs.mem")))

    tb = (TB_TEMPLATE
          .replace("__NUM_CASES__", str(ncases))
          .replace("__MSG_N__", str(msgs_n))
          .replace("__DIG_N__", str(digs_n)))

    tb_path = os.path.join(BUILD, "tb_kat.sv")
    with open(tb_path, "w") as f:
        f.write(tb)

    sim = os.path.join(BUILD, "kat.vvp")
    subprocess.check_call([
        "iverilog", "-g2012", "-o", sim,
        os.path.join(ROOT, "rtl", "keccak.v"),
        os.path.join(ROOT, "rtl", "keccak_engine.v"),
        os.path.join(ROOT, "rtl", "sha3.v"),
        tb_path], cwd=ROOT)

    out = subprocess.check_output(["vvp", sim], cwd=ROOT, text=True)
    result_line = None
    for line in out.splitlines():
        if line.startswith("KAT_RESULT"):
            result_line = line
        elif line.startswith("KAT FAIL"):
            print(line)
    if result_line is None:
        print("error: no KAT_RESULT in simulation output")
        return 1
    print(result_line)

    m = re.search(r"pass=(\d+) fail=(\d+)", result_line)
    if m is None:
        print("error: malformed KAT_RESULT line")
        return 1
    npass, nfail = int(m.group(1)), int(m.group(2))
    if nfail == 0:
        print(f"PASS: {npass}/{npass} KAT vectors passed")
        return 0
    print(f"FAIL: {nfail} KAT vectors failed")
    return 1


if __name__ == "__main__":
    sys.exit(main())
